### ISSUE TITLE
Cannot deploy MobileFirstBankAuthAdapter

### ISSUE THREAD

**Issue by prem911** [MobileFirst-Platform-Developer-Center/MobileFirstBankCordova#1]
Downloaded the AuthAdapter from the link.
mfpdev adapter build was correct.
mfpdev adapter deploy failed.

I passed -d option and this is the log.

[DeployError.txt](https://github.com/MobileFirst-Platform-Developer-Center/MobileFirstBankCordova/files/420008/DeployError.txt)

**Comment by IdanAdar** [comment]
That is an inappropriate way to ask a question. Please provide details, steps to reproduce...
