### ISSUE TITLE
Unable to sign into app on iOS

### ISSUE THREAD

**Issue by gregackerman** [MobileFirst-Platform-Developer-Center/MobileFirstBankCordova#2]
I have cloned the repo and completed the setup steps in README.MD.  I have added an iOS and an Android platform to the Cordova project and registered both to the MFP Server.  When I emulate the application in an AVD, it works fine and I can log in with username and password.  When I emulate in iOS sim or run on an iOS physical device, I cannot enter username and password into the fields.  I type but the text does not appear, and therefore cannot go further.  Thanks for the help looking into this one.

**Comment by ynunez** [comment]
Hi @gregackerman I've implemented a fix for that issue, we just need to marge the changes.

**Comment by IdanAdar** [comment]
@gregackerman, please test. 
If the app now works, please close this issue.

**Comment by gregackerman** [comment]
Yes this works now on a real device.  On simulator I can type in text for UID and password and then click submit with no action for some reason.  I would call this issue closed for the original issue - thanks again.
